FROM node as chromeready
RUN wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -
RUN sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list'
ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update && apt-get install -yq google-chrome-stable

FROM chromeready as builder
WORKDIR /app
COPY . .
RUN npm i
ENV PATH=/app/node_modules/.bin:$PATH
#Commented out for dev envirnonment for speed of deployment until
#CICD is implemented.
#RUN ng test --browsers ChromeHeadless --watch=false
RUN ng build

FROM nginx
COPY --from=builder /app/dist/protein-expression-front-end /usr/share/nginx/html
EXPOSE 80
